apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orion-prod
resources:
  - ../base
configMapGenerator:
  - name: api-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=warn
  - name: worker-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - CRON_SCHEDULE=0 0 * * *
images:
  - name: orion-api
    newName: ghcr.io/orionlynn19/orion-api
    newTag: latest
  - name: orion-worker
    newName: ghcr.io/orionlynn19/orion-worker
    newTag: latest