apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orion-prod
resources:
  - ../../base

images:
  - name: orion-api
    newName: ghcr.io/orionlynn19/orion-api
    newTag: latest
  - name: orion-worker
    newName: ghcr.io/orionlynn19/orion-worker
    newTag: latest