apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agnos-prod
resources:
  - ../../base
configMapGenerator:
  - name: api-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=warn
  - name: worker-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - CRON_SCHEDULE=0 0 * * *
images:
  - name: agnos-api
    newTag: prod
  - name: agnos-worker
    newTag: prod