apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  NODE_ENV: "development"
  PORT: "8000"
  LOG_LEVEL: "debug"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
data:
  NODE_ENV: "development"
  METRICS_PORT: "9091"
  CRON_SCHEDULE: "* * * * *"
  TZ: "UTC"