apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agnos-uat
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: api
configMapGenerator:
  - name: api-config
    behavior: merge
    literals:
      - NODE_ENV=uat
      - LOG_LEVEL=info
  - name: worker-config
    behavior: merge
    literals:
      - NODE_ENV=uat
images:
  - name: agnos-api
    newTag: uat
  - name: agnos-worker
    newTag: uat