apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orion-dev
resources:
  - ../base
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: api
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
    target:
      kind: HorizontalPodAutoscaler
      name: api-hpa
configMapGenerator:
  - name: api-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - LOG_LEVEL=debug
  - name: worker-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - CRON_SCHEDULE=* * * * *
images:
  - name: orion-api
    newName: ghcr.io/orionlynn19/orion-api
    newTag: dev
  - name: orion-worker
    newName: ghcr.io/orionlynn19/orion-worker
    newTag: dev